# goal

# definitions of possible values to use as type
uint8 UNDEFINED=0
uint8 PLAN_AND_EXECUTE=1
uint8 PLAN_ONLY=2

# use one of the above constants to indicate the goal type
uint8 type

# sequence of movement commands to execute
giskard_msgs/MoveCmd[] cmd_seq
---
# result
# definition of possible error code values
uint8 SUCCESS=0
uint8 INSOLVABLE=1 # usually means that giskard thinks that the robot is out of joint limits
uint8 PATH_COLLISION=2 # not implemented
uint8 START_STATE_COLLISION=3 # not implemented
uint8 END_STATE_COLLISION=4 # not implemented
uint8 SOLVER_TIMEOUT=5 # not implemented
uint8 INTERRUPTED=6 # goal got cancled via action server interface
uint8 MAX_NWSR_REACHED=7 # increasing NWSR might fix this
uint8 QP_SOLVER_ERROR=8 # delete your robot folger in giskardpy/data and try again
uint8 UNKNOWN_OBJECT=9
uint8 SYMENGINE_ERROR=10

# error codes for the overall action goal
uint8 error_code

# planned trajectory
trajectory_msgs/JointTrajectory trajectory
---
# feedback

# definitions of possible action phases
uint8 UNDEFINED=0
uint8 INIT_KINEMATIC_CHAIN=1 # not implemented
uint8 PLANNING=2
uint8 EXECUTION=3

# action phase that the server currently pursues
uint8 phase

# value between 0.0 and 1.0 to report progress 
# only published during phases EXECUTION
float64 progress
